In [1]:
for i in range(1,5):
    for j in range(1,i+1):
        print("*",end=" ")
    print()

* 
* * 
* * * 
* * * * 


In [2]:
for i in range(0,4):
    for j in range(0,4):
        if(i+j>=3):
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()

      * 
    * * 
  * * * 
* * * * 


In [3]:
name=input('Enter name: ')
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end='')
    print()

Enter name: virat
v
ii
rrr
aaaa
ttttt


In [4]:
rec={}
n=int(input("Enter no.of students"))
i=1
while i<=n:
    name=input("Enter student name:")
    marks=input("Enter % marks of students")
    rec[name]=marks
    i+=1
print(" name of the student","\t","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

Enter no.of students1
Enter student name:shree
Enter % marks of students94
 name of the student 	 % of marks
	 shree 		 94


In [5]:
d={'mango':1,'apple':2}
len(d)

2

In [6]:
d.clear()

In [7]:
del d

In [8]:
word=input("Enter any word")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occur",v,"times")

Enter any wordshreeya
s occur 1 times
h occur 1 times
r occur 1 times
e occur 2 times
y occur 1 times
a occur 1 times


In [9]:
word=input("Enter any word")
d={}
for x in word:
    if x=='a':
        d[x]=d.get(x,0)+1
    elif x=='e':
        d[x]=d.get(x,0)+1
    elif x=='i':
        d[x]=d.get(x,0)+1
    elif x=='o':
        d[x]=d.get(x,0)+1
    elif x=='u':
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occur",v,"times") 

Enter any wordshreeya
e occur 2 times
a occur 1 times


In [10]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [11]:
word=input("Enter any word")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occur",v,"times") 
        

Enter any wordshreeya
e occur 2 times
a occur 1 times


In [17]:
n=[1,2,3,4,5,6,6,7,7,7,7]
print(n.count(6))
print(n.index(4))

2
3


In [20]:
n.insert(1,127)

In [21]:
print(n)

[1, 127, 1627, 2, 3, 4, 5, 6, 6, 7, 7, 7, 7]


In [27]:
l1=[1,2,3,'shree']
l2=[4,5,6,'anu']
print(l1)
l1.extend(l2)
print(l2)
print(l1)

[1, 2, 3, 'shree']
[4, 5, 6, 'anu']
[1, 2, 3, 'shree', 4, 5, 6, 'anu']


### extend

In [28]:
l1.reverse()

In [30]:
print(l1)

['anu', 6, 5, 4, 'shree', 3, 2, 1]


In [33]:
l3=['shree','anu','nishi','aksh']
l3.sort()
print(l3)

['aksh', 'anu', 'nishi', 'shree']


In [34]:
l2.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

In [35]:
l3.sort(reverse=True)
print(l3)

['shree', 'nishi', 'anu', 'aksh']


In [39]:
x=[10,20,30,40,50]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40, 50]
[10, 777, 30, 40, 50]


In [40]:
x=[10,20,30,40,50]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40, 50]
[10, 777, 30, 40, 50]


In [41]:
x=[10,20,30,40,50]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40, 50]
[10, 777, 30, 40, 50]


In [42]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [43]:
c=a*3
print(c)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [47]:
x=["MITE","YIT","NITTE"]
y=["MITE","YIT","NITTE"]
x==y
x!=y
z=["MITE","YIT","AIT"]
x==z
x!=z


True

In [48]:
m=[10,20,30,[50,60,70]]
m[3]

[50, 60, 70]

In [49]:
m[2]

30

In [51]:
m[3][2]

70

In [52]:
m.clear()

In [53]:
n=[1,2,3,4]
print(4 in n)

True


In [55]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [57]:
word=["MITE","BANGALORE","SHREE"]
l=[w[0] for w in word]
print(l)

['M', 'B', 'S']


In [59]:
def times2(var):
    return var*2
seq=[1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [64]:
seq=[1,2,3,4,5,6,7,8]
lambda var: var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4, 6, 8]

In [65]:
import numpy as np
lst=[1,2,3]
lst
np.array(lst)

array([1, 2, 3])

In [66]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [70]:
np.zeros(3)

array([0., 0., 0.])

In [71]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [77]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.random.rand(2)

array([0.44510782, 0.96207569])

In [79]:
np.random.rand(5,5)

array([[0.14984373, 0.20333845, 0.44439139, 0.94907185, 0.73193015],
       [0.62620084, 0.88553739, 0.86073843, 0.56625693, 0.65482465],
       [0.40921469, 0.64293249, 0.55455448, 0.74118901, 0.92245332],
       [0.30515768, 0.5123787 , 0.44512522, 0.48663791, 0.71297165],
       [0.8600073 , 0.45121789, 0.42217984, 0.84597837, 0.17388557]])

In [80]:
np.random.randn(5,5)

array([[-0.08652919,  0.2376373 , -0.42174788,  0.33292455, -0.63595785],
       [-0.51234856, -1.46321495, -0.35168943, -1.39427306,  1.24994862],
       [-0.35257246,  0.45828763, -0.85548635,  2.16201276, -1.24007463],
       [-0.41690134,  1.50540923, -1.06965995,  2.34771567,  2.4301729 ],
       [-0.50432698, -0.16901723, -1.21981269,  0.3451858 , -2.04644107]])

In [84]:
np.random.randint(1,100,10)

array([64, 37, 83, 93, 65, 20, 98, 61, 79, 71])

In [86]:
ar=np.random.randint(1,100,10)
print(ar)

[97 41 66 87 81 90 13 44 70 11]


In [87]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)


In [89]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
runarr.max()

48

In [91]:
runarr.argmax()

6

In [92]:
runarr.argmin()

9

In [94]:
runarr.min()

4

In [96]:
arr.shape

(25,)

In [97]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [98]:
arr.reshape(1,25).shape

(1, 25)

In [99]:
arr.reshape(25,1).shape

(25, 1)

In [100]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [101]:
arr.dtype

dtype('int32')

In [102]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [103]:
arr=np.arange(0,10)

In [104]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [105]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [106]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
arr/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [109]:
1/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [110]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [111]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [112]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [113]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [114]:
np.log(arr)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [116]:
arr=np.arange(0,11)

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
arr[8]

8

In [119]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [120]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [121]:
arr[0:5]=100

In [122]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [124]:
arr>40


array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [126]:
arr[arr>6]

array([100, 100, 100, 100, 100,   7,   8,   9,  10])

In [127]:
np.zeros((12))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
np.ones((15))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [132]:
5*np.ones((10))

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [133]:
np.arange(10,80,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [135]:
arr=np.arange(0,9)
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
arr=np.arange(1,26)
arr.reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [139]:
arr[arr>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [140]:
np.random.randn(5,5)

array([[-0.74229095, -0.29528791,  1.40263943, -0.73974083, -0.99430791],
       [-1.39619696,  3.02018983,  0.57331391,  1.8056996 , -1.069657  ],
       [-1.8595316 , -0.1079015 , -1.02785663, -1.43575272,  0.1919798 ],
       [ 0.674874  ,  1.22802251,  1.56752783, -0.50813713,  0.36181328],
       [ 0.03347954, -1.32663955,  0.8147567 ,  0.54072729,  1.21883641]])